import Header from "@/components/header";
import "./index.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div 
        // style={{ marginTop: "150px" }}
        >{children}</div>
      </body>
    </html>
  );
}
